"""JavaScript/TypeScript AST analysis using tree-sitter.

Walks the tree-sitter parse tree to extract function declarations that
overlap with the changed line set in a diff. Follows the same design as
the Kotlin analyzer (lazy parser import, generated-file detection,
outermost-function attribution).

Grammar selection by extension:
- ``.js`` / ``.jsx`` / ``.mjs`` / ``.cjs`` → tree-sitter-javascript
  (JSX is part of the core JavaScript grammar)
- ``.ts`` → tree-sitter-typescript's ``language_typescript()``
- ``.tsx`` → tree-sitter-typescript's ``language_tsx()``

Function shapes recognized (verified against tree-sitter-javascript
0.21.x / tree-sitter-typescript 0.21.x node types):
- ``function_declaration`` / ``generator_function_declaration``
- ``method_definition`` inside a ``class_body`` (qualified ``Class.method``)
- ``field_definition`` / ``public_field_definition`` whose value is an
  arrow function (class property methods, common in React/TS code)
- ``variable_declarator`` whose value is an ``arrow_function`` or
  ``function_expression`` (``const foo = () => ...``), including inside
  ``export_statement`` wrappers
- ``assignment_expression`` like ``module.exports.foo = function ...``
  or ``exports.foo = () => ...``

Attribution rule: a changed line is attributed to the OUTERMOST
function that contains it. We never descend into an emitted function,
so an edit inside a nested callback is reported as a change to the
enclosing named function — which is the unit a test actually exercises.
"""

from __future__ import annotations

import os
from functools import lru_cache

from test_automator.models import AffectedFunction
from test_automator.utils.exceptions import CodeAnalyzerError

# Strong markers — these alone are sufficient to mark a file as generated.
_STRONG_GENERATED_MARKERS = (
    "@generated",
    "GENERATED CODE",
    "AUTO-GENERATED",
    "This file was automatically generated",
    "This file is auto-generated",
    "// Generated by",
    "/* eslint-disable */ // prettier-ignore-file generated",
)

# Node types that declare a function directly.
_DIRECT_FUNCTION_TYPES = (
    "function_declaration",
    "generator_function_declaration",
)

# Node types whose VALUE may be a function (const foo = () => ...).
_FUNCTION_VALUE_TYPES = (
    "arrow_function",
    "function_expression",
    "function",  # older grammar name for function expressions
    "generator_function",
)


@lru_cache(maxsize=4)
def _get_parser(dialect: str):
    """Lazily construct a tree-sitter parser for the given dialect
    ("javascript", "typescript", or "tsx").

    Cached per dialect. Raises CodeAnalyzerError with an actionable
    install hint if the optional dependencies aren't installed.
    """
    try:
        from tree_sitter import Language, Parser

        if dialect == "javascript":
            import tree_sitter_javascript as ts_lang

            capsule = ts_lang.language()
        elif dialect == "typescript":
            import tree_sitter_typescript as ts_ts

            capsule = ts_ts.language_typescript()
        elif dialect == "tsx":
            import tree_sitter_typescript as ts_ts

            capsule = ts_ts.language_tsx()
        else:
            raise CodeAnalyzerError(f"Unknown JS dialect: {dialect!r}")
    except ImportError as exc:
        raise CodeAnalyzerError(
            "JavaScript/TypeScript parsing requires the 'tree-sitter', "
            "'tree-sitter-javascript' and 'tree-sitter-typescript' "
            "packages. Install them with:\n"
            "  pip install tree-sitter tree-sitter-javascript "
            "tree-sitter-typescript\n"
            f"Underlying error: {exc}"
        ) from exc

    return Parser(Language(capsule))


def _dialect_for(file_path: str) -> str:
    ext = os.path.splitext(file_path)[1].lower()
    if ext == ".ts":
        return "typescript"
    if ext == ".tsx":
        return "tsx"
    return "javascript"


def is_generated(source_code: str, file_path: str = "") -> bool:
    """True if the file appears tool-generated or is not testable source.

    ``.d.ts`` files are type declarations (no runtime behavior to test)
    and ``.min.js`` files are bundler output.
    """
    if file_path.endswith(".d.ts") or file_path.endswith(".min.js"):
        return True
    head = source_code[:4096]
    return any(marker in head for marker in _STRONG_GENERATED_MARKERS)


def extract_affected(
    source_code: str,
    file_path: str,
    changed_lines: set[int],
) -> list[AffectedFunction]:
    """Return functions/methods overlapping ``changed_lines``.

    Includes top-level functions, arrow functions bound to const/let/var,
    class methods (qualified ``Class.method``), class property arrows,
    and ``module.exports.x = fn`` assignments.
    """
    if is_generated(source_code, file_path):
        return []

    parser = _get_parser(_dialect_for(file_path))
    source_bytes = source_code.encode("utf-8")

    try:
        tree = parser.parse(source_bytes)
    except Exception as exc:
        raise CodeAnalyzerError(
            f"JavaScript/TypeScript parse failed in {file_path}: {exc}"
        ) from exc

    source_lines = source_code.splitlines()
    results: list[AffectedFunction] = []
    _walk(
        tree.root_node,
        source_bytes,
        source_lines,
        changed_lines,
        file_path,
        class_stack=[],
        results=results,
    )
    return results


def extract_class_signatures(source_code: str, file_path: str = "x.js") -> str:
    """Return class/function signature lines from the file, no bodies.

    Same purpose as the Kotlin handler's version: give the LLM the real
    constructor and method signatures so it doesn't hallucinate them.
    For classes we emit the ``class Foo ... {`` line plus one line per
    method signature; for top-level functions and function-valued
    consts we emit their first line.
    """
    try:
        parser = _get_parser(_dialect_for(file_path))
        tree = parser.parse(source_code.encode("utf-8"))
    except Exception:
        return ""

    lines = source_code.splitlines()
    sigs: list[str] = []

    def first_line(node) -> str:
        row = node.start_point[0]
        return lines[row].strip() if row < len(lines) else ""

    def visit(node) -> None:
        if node.type in ("class_declaration", "abstract_class_declaration"):
            sigs.append(first_line(node))
            body = _child_of_type(node, "class_body")
            if body is not None:
                for member in body.children:
                    if member.type == "method_definition" or member.type in (
                        "field_definition",
                        "public_field_definition",
                    ):
                        sigs.append("    " + first_line(member).rstrip("{").rstrip())
            sigs.append("}")
            return
        if node.type in _DIRECT_FUNCTION_TYPES:
            sigs.append(first_line(node).rstrip("{").rstrip())
            return
        if node.type in ("lexical_declaration", "variable_declaration"):
            decl = _child_of_type(node, "variable_declarator")
            if decl is not None and _declarator_function(decl) is not None:
                sigs.append(first_line(node).rstrip("{").rstrip())
            return
        for child in node.children:
            visit(child)

    visit(tree.root_node)
    return "\n".join(s for s in sigs if s)


# ---------------------------------------------------------------------------
# Walker
# ---------------------------------------------------------------------------


def _walk(
    node,
    source_bytes: bytes,
    source_lines: list[str],
    changed_lines: set[int],
    file_path: str,
    class_stack: list[str],
    results: list[AffectedFunction],
) -> None:
    node_type = node.type

    # Unwrap export statements: `export function foo`, `export default ...`,
    # `export const foo = () => ...`
    if node_type == "export_statement":
        for child in node.children:
            _walk(
                child, source_bytes, source_lines, changed_lines,
                file_path, class_stack, results,
            )
        return

    if node_type in _DIRECT_FUNCTION_TYPES:
        name = _identifier_text(node.child_by_field_name("name"), source_bytes)
        if name:
            _emit_if_overlapping(
                node, name, "function", source_lines, changed_lines,
                file_path, class_stack, results,
            )
        return  # never descend into a function

    if node_type in ("class_declaration", "abstract_class_declaration"):
        name = _identifier_text(node.child_by_field_name("name"), source_bytes)
        body = _child_of_type(node, "class_body")
        if body is not None:
            class_stack.append(name or "AnonymousClass")
            for member in body.children:
                _walk(
                    member, source_bytes, source_lines, changed_lines,
                    file_path, class_stack, results,
                )
            class_stack.pop()
        return

    if node_type == "method_definition":
        name = _identifier_text(node.child_by_field_name("name"), source_bytes)
        if name:
            _emit_if_overlapping(
                node, name, "method", source_lines, changed_lines,
                file_path, class_stack, results,
            )
        return

    if node_type in ("field_definition", "public_field_definition"):
        value = node.child_by_field_name("value")
        if value is not None and value.type in _FUNCTION_VALUE_TYPES:
            name = _identifier_text(
                node.child_by_field_name("name")
                or node.child_by_field_name("property"),
                source_bytes,
            )
            if name:
                _emit_if_overlapping(
                    node, name, "method", source_lines, changed_lines,
                    file_path, class_stack, results,
                )
        return

    if node_type in ("lexical_declaration", "variable_declaration"):
        for decl in node.children:
            if decl.type != "variable_declarator":
                continue
            fn_value = _declarator_function(decl)
            if fn_value is None:
                continue
            name = _identifier_text(
                decl.child_by_field_name("name"), source_bytes
            )
            if name:
                # Use the whole declaration statement's range so the
                # `const foo = ` prefix is part of the source shown to
                # the LLM.
                _emit_if_overlapping(
                    node, name, "arrow_function", source_lines,
                    changed_lines, file_path, class_stack, results,
                )
        return

    if node_type == "expression_statement":
        # module.exports.foo = function ... / exports.foo = () => ...
        expr = node.children[0] if node.children else None
        if expr is not None and expr.type == "assignment_expression":
            right = expr.child_by_field_name("right")
            left = expr.child_by_field_name("left")
            if (
                right is not None
                and right.type in _FUNCTION_VALUE_TYPES
                and left is not None
            ):
                name = _member_expression_property(left, source_bytes)
                if name:
                    _emit_if_overlapping(
                        node, name, "function", source_lines,
                        changed_lines, file_path, class_stack, results,
                    )
                    return
        # fall through: other expression statements aren't functions
        return

    for child in node.children:
        _walk(
            child, source_bytes, source_lines, changed_lines,
            file_path, class_stack, results,
        )


def _emit_if_overlapping(
    node,
    name: str,
    kind: str,
    source_lines: list[str],
    changed_lines: set[int],
    file_path: str,
    class_stack: list[str],
    results: list[AffectedFunction],
) -> None:
    line_start = node.start_point[0] + 1
    line_end = node.end_point[0] + 1
    if not any(line_start <= ln <= line_end for ln in changed_lines):
        return

    source_code = "\n".join(source_lines[line_start - 1 : line_end])
    qualified = ".".join([*class_stack, name])
    results.append(
        AffectedFunction(
            file_path=file_path,
            name=name,
            qualified_name=qualified,
            kind=kind,
            source_code=source_code,
            line_start=line_start,
            line_end=line_end,
        )
    )


# ---------------------------------------------------------------------------
# Node helpers
# ---------------------------------------------------------------------------


def _identifier_text(node, source_bytes: bytes) -> str | None:
    if node is None:
        return None
    text = source_bytes[node.start_byte : node.end_byte].decode("utf-8")
    # Computed property names ([Symbol.iterator]) and string-literal
    # names ('some name') aren't useful test targets — skip them.
    if text.startswith("[") or text.startswith(("'", '"')):
        return None
    return text or None


def _child_of_type(node, type_name: str):
    for child in node.children:
        if child.type == type_name:
            return child
    return None


def _declarator_function(decl):
    """If a variable_declarator's value is a function, return that value
    node, else None. TS may wrap the function in an `as` expression or
    parentheses; unwrap one level of those.
    """
    value = decl.child_by_field_name("value")
    if value is None:
        return None
    if value.type in ("as_expression", "parenthesized_expression"):
        for child in value.children:
            if child.type in _FUNCTION_VALUE_TYPES:
                return child
        return None
    if value.type in _FUNCTION_VALUE_TYPES:
        return value
    return None


def _member_expression_property(node, source_bytes: bytes) -> str | None:
    """For `module.exports.foo` / `exports.foo` / `Foo.prototype.bar`,
    return the final property name (foo / bar).
    """
    if node.type != "member_expression":
        return None
    prop = node.child_by_field_name("property")
    return _identifier_text(prop, source_bytes)
